import Product from "../models/Product.js";

// @desc    Ingest and save a new product to MongoDB
// @route   POST /api/products/addproduct
export const addProduct = async (req, res) => {
  try {
    // 1. Fetch all products from the database to calculate an auto-incrementing custom ID
    let products = await Product.find({});
    let id;
    
    if (products.length > 0) {
      // Grab the last element in the returned array and increment its ID by 1
      let last_product_array = products.slice(-1);
      let last_product = last_product_array[0];
      id = last_product.id + 1;
    } else {
      id = 1; // Fallback sequence to ID 1 if this is the absolute first record in the collection
    }

    // 2. Instantiate a new database document based on our Mongoose model schema
    const product = new Product({
      id: id,
      name: req.body.name,
      image: req.body.image,       // The static host link generated by your Multer engine
      category: req.body.category,
      new_price: req.body.new_price,
      old_price: req.body.old_price,
    });

    // 3. Commit the record block to your MongoDB cluster
    await product.save();
    console.log(`📦 DB Success: Product saved successfully -> ${product.name}`);
    
    // 4. Return execution status response to the calling frontend
    res.json({ 
      success: true, 
      name: req.body.name 
    });
    
  } catch (error) {
    console.error("❌ Add Product Error Context:", error);
    res.status(500).json({ 
      success: false, 
      message: "Database insertion pipeline failure" 
    });
  }
};


// @desc    Purge and erase an item from MongoDB by ID SKU reference
// @route   POST /api/products/removeproduct
export const removeProduct = async (req, res) => {
  try {
    // Look up the exact object matching the tracking ID parameters and clear it out
    const deletedProduct = await Product.findOneAndDelete({ id: req.body.id });
    
    if (!deletedProduct) {
      return res.status(404).json({ 
        success: false, 
        message: "No product matches the requested ID sequence" 
      });
    }

    console.log(`🗑️ DB Success: Product SKU-${req.body.id} has been fully deleted.`);
    
    res.json({ 
      success: true, 
      message: "Product removed successfully" 
    });
    
  } catch (error) {
    console.error("❌ Remove Product Error Context:", error);
    res.status(500).json({ 
      success: false, 
      message: "Database deletion pipeline failure" 
    });
  }
};

// @desc    Fetch all products from MongoDB database collection
// @route   GET /api/products/allproducts
export const getAllProducts = async (req, res) => {
  try {
    let products = await Product.find({});
    console.log(`🔍 DB Read: Retrieved ${products.length} products from the catalog.`);
    res.json(products);
  } catch (error) {
    console.error("❌ Fetch All Products Error:", error);
    res.status(500).json({ success: false, message: "Database read failure" });
  }
};

// @desc    Get latest added products for New Collections section
// @route   GET /api/products/newcollections
export const getNewCollections = async (req, res) => {
  try {
    let products = await Product.find({});
    // Slice the last 8 uploaded products from the array database record entries
    let newcollections = products.slice(-8);
    console.log("🔍 DB Read: Retrieved latest 8 collection entries.");
    res.json(newcollections);
  } catch (error) {
    console.error("❌ New Collections Fetch Error:", error);
    res.status(500).json({ success: false, message: "Server error fetching collections" });
  }
};

// @desc    Get popular products in the men's category (or women's based on front needs)
// @route   GET /api/products/popularinmen
export const getPopularInMen = async (req, res) => {
  try {
    let products = await Product.find({ category: "mens" });
    let popular_in_men = products.slice(0, 4); // Grabs the first 4 items as featured units
    res.json(popular_in_men);
  } catch (error) {
    console.error("❌ Popular Items Fetch Error:", error);
    res.status(500).json({ success: false, message: "Server error fetching popular items" });
  }
};